[package]
name = "keyboard"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-executor = { version = "0.9", features = [ "arch-cortex-m", "executor-thread"]}
embassy-rp = { version = "0.10.0", features = ["time-driver", "critical-section-impl", "rp2040"] }
embassy-time = { version = "0.5", features = ["log"] }
embassy-usb = {version = "0.6.0"}

embassy-usb-logger={version = "0.6.0"}
panic-probe = { version = "1.0.0" }
cortex-m-rt = "0.7.5"
embassy-futures = "0.1"
static_cell = "2.1"
portable-atomic = { version = "1.14", features = ["critical-section"] }
heapless = "0.9.3"


log = "0.4.33"

